### ISSUE TITLE
C# 6 Support

### ISSUE THREAD

**Issue by SeriousM** [continuoustests/ContinuousTests#22]
Hi! The tool looks promissing and I want to try it out.
My project uses the C# 6 features like string interpolation (`$"{count} elements"`) and null propagation (`User?.Name`).

When I build I get the error `CS1056: Unexpected character '$'`.

Any plans to support C# 6 features in the near future?

Thanks

**Comment by SeriousM** [comment]
It turns out that the support can easily get enabled by defining the `msbuild.exe` in the `C:\Users\<username>\AppData\Local\MightyMoose\AutoTest.config` to `C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe`.

**Comment by apuchkov** [comment]
Just faced this problem as well. Thanks for solution @SeriousM!

**Comment by SeriousM** [comment]
> Just faced this problem as well.

Thats why I always write a solution to my questions (if available) instead closing them without any help :)
