### ISSUE TITLE
No (clear) way to set the watched path (?)

### ISSUE THREAD

**Issue by taharrison** [continuoustests/ContinuousTests#25]
Running continuous tests desktop application, can't find out how to set it to monitor my solution.
I've clicked through every option page, read all the config files, and was considering debugging.

I must have missed something, but the documentation is very lacking.

Options for improving this include updating the project README markdown, some first-use instructions, or having some help text available the whole time the status is "0 builds, 0 tests"

I am happy to create a pull request for the solution if someone can point me in the right direction.
Currently cannot use the app at all.

**Comment by acken** [comment]
You spesify the watch path / solution file when starting continsuous tests as the first agrument to the application.

**Comment by taharrison** [comment]
Not certain you should close this issue.  It isn't documented to the end user and isn't clear.  The resolution should be to add this info.
